---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: buildpacks
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request, push]"
    pipelinesascode.tekton.dev/on-target-branch: "pac-buildpack-build"

    pipelinesascode.tekton.dev/task: "git-clone"
    pipelinesascode.tekton.dev/task-1: "[https://raw.githubusercontent.com/ch007m/tekton-pac/main/k8s/task-builpack-phases.yml]"
    pipelinesascode.tekton.dev/task-2: "maven"
    pipelinesascode.tekton.dev/task-3: "kubernetes-actions"

    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  serviceAccountName: default
  params:
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
    workspaces:
      - name: source
      - name: basic-auth
      - name: temp
      - name: cache
    tasks:
      - name: fetch-repository
        taskRef:
          name: git-clone
        workspaces:
          - name: output
            workspace: source
          - name: basic-auth
            workspace: basic-auth
        params:
          - name: url
            value: $(params.repo_url)
          - name: revision
            value: $(params.revision)
      - name: buildpacks
        taskRef:
          name: buildpacks-phases
        runAfter:
          - fetch-repository
        params:
          - name: APP_IMAGE
            value: ttl.sh/c04768cb-2012-4280-990d-a9adf51c7462:2h
          - name: CNB_BUILDER_IMAGE
            value: paketobuildpacks/builder:0.1.361-tiny # gcr.io/paketo-buildpacks/builder:0.1.361-tiny
          - name: CNB_LIFECYCLE_IMAGE
            value: buildpacksio/lifecycle:0.16.3
          - name: RUN_IMAGE
            value: paketobuildpacks/run:tiny
          - name: ENV_VARS
            value:
              - "BP_NATIVE_IMAGE=false"
              - "BP_MAVEN_BUILT_ARTIFACT=func.yaml target/quarkus-app/lib/ target/quarkus-app/*.jar target/quarkus-app/app/ target/quarkus-app/quarkus/"
              - "BP_MAVEN_BUILD_ARGUMENTS=package -DskipTests=true -Dmaven.javadoc.skip=true -Dquarkus.package.type=fast-jar"
        workspaces:
          - name: source
            workspace: source
          - name: cache
            workspace: cache
  workspaces:
    - name: cache
      subPath: cache
      persistentVolumeClaim:
        claimName: cache-volume-ws-pvc
    - name: temp
      subPath: temp
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: source
      subPath: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: basic-auth
      secret:
        secretName: "{{ git_auth_secret }}"
    - name: maven-settings
      emptyDir: {}